openapi: 3.0.3
info:
    title: VWT Backend API
    description: Backend API used for the VWT project.
    termsOfService: http://swagger.io/terms/
    contact:
        email: thiguet2014@gmail.com
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    version: 1.0.0
externalDocs:
    description: Find out more about Swagger
    url: http://swagger.io
servers:
    - url: /api/v1
