version: '3.7'

services:
    postgres-compose:
        image: postgres
        environment:
            POSTGRES_DB: vwt
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Postgres2019!
        ports:
            - '15432:5432'
        volumes:
            - pg1:/var/lib/postgresql/data
            - pg2:/etc/postgresql
            - pg3:/var/log/postgresql
        networks:
            - postgres-compose-network

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'PgAdmin2019!'
        ports:
            - '16543:80'
        depends_on:
            - postgres-compose
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge

volumes:
    pg1:
        driver: local
    pg2:
        driver: local
    pg3:
        driver: local
